### ISSUE TITLE
Implementation with d3 Version 6

### ISSUE THREAD

**Issue by smithGit** [UW-Macrostrat/geo-timescale#3]
This is a great application.  I am having difficulty converting to d3 V6, in the .drag operation - the .origin operation gets "not a function" error.  A working V6 version or pointer to examples of d3 drag with .origin would be appreciated.  Thanks!

Code not working:
      //var drag = d3.behavior.drag()  << code from V3
      var drag = d3.drag()
        .origin(function() {    // << Command throwing not a function error
          var t = d3.select(".timescale g");
          return {x: -newX, y: 0};
        })
        .on("start", (event, d) => {
          dragStart = [d3.event.sourceEvent.pageX, d3.event.sourceEvent.pageY];
          transformStart = d3.transform(d3.select(".timescale").select("g").attr("transform")).translate;
          d3.event.sourceEvent.stopPropagation();
        })
        .on("drag", (event, d) => {
          var currentDrag = [d3.event.sourceEvent.pageX, d3.event.sourceEvent.pageY];
          newX = (dragStart[0] - currentDrag[0]);
          d3.select(".timescale").select("g")
            .attr("transform", function() {
              return "translate(" + [ parseInt(transformStart[0] + -newX), 0 ] + ")scale(" + 
            });
        });

**Comment by davenquinn** [comment]
Hi, thanks for bringing this up. It's been a while, but I remember trying to upgrade `d3.drag` code for some other projects. The breaking change was introduced in d3 v4 with a whole raft of others.

I believe the main culprit was the removal of `.origin` and replacment with `.subject` which does the same thing but differently. [This StackOverflow answer](https://stackoverflow.com/questions/38599930/d3-version-4-workaround-for-drag-origin) might help figure out how to move forward.

We'd appreciate a pull request if you end up figuring this out and implementing a fix!

Also, side note, but you might be interested in our newer [React library](https://github.com/UW-Macrostrat/timescale) that does similar things ([example](https://davenquinn.com/viz/corelle-demo-pbdb/?time=283))

**Comment by smithGit** [comment]
Thanks for your response!  I will get right on this tomorrow; I have seen nothing on .subject, so thanks for this pointer (I am going from V3 straight to V6).  An additional complication is that all the d3 examples now are done with Observable, which are hard to work back into JavaScript mode.  Observable is good, but many d3 users, including me, just want to stick with their existing methods and huge apps already done in Node-React-Vue.js-etc.  Sam

**Comment by JulesBlm** [comment]
I converted this to work in d3 v5 a few years back, see this pull request I made for it: [d3 v5 version w concurrent animations](https://github.com/UW-Macrostrat/geo-timescale/pull/2), the [live plain D3.js demo](http://bl.ocks.org/JulesBlm/raw/a25026573de31ea91a2a779d3366929b/) or the 
[Observable notebook](https://observablehq.com/@julesblm/geological-timescale). D3 v6 breaks some stuff again, I haven’t looked in to it much but I suspect that issue is that v6 handles events differently. In any case the ste from v5 to v6 or v7 is a lot smaller than from v3. Let me know if you’re still working on this, I’m willing to help. There’s also an ICS update that I would like to include.

**Comment by smithGit** [comment]
Wonderful,  Dank u zeer!  I would be most interested in a D3 V6 (yikes - do in V7 as it is current and would seem like a small change from D6 for this app) implementation that includes the slightly updated ICS timeline names (which I have but cannot recall what they are), as both plain JS and Observable.  I am in touch with folks in Queensland who are involved in the ICS activities, and I am sure they would also be interested.  What I am thinking is to take your Observable notebook and enhance it to reflect a collaborative project - with a notebook describing the ICS and steps leading up to your implementation.  
I have a not-very-good implementation.  Yours is much better, but it shows the descriptive info I would like to suggest. 
https://observablehq.com/d/f5509b43eb703e68
Sam in Michigan

**Comment by JulesBlm** [comment]
Great, thanks for your interest. I’ll have some spare time next week I’ll take a look next week and start converting it to v7 then. Btw I can’t view the notebook in link you included. Perhaps the notebook isn’t published yet?

**Comment by JulesBlm** [comment]
I found some time to work on it and made steady progress, see this Observable notebook: [Geological Time Scale 2021](https://observablehq.com/@julesblm/geological-time-scale-2021).

I've refactored the code quite a lot. It now uses D3 v7 and the code is a lot more idiomatic D3 code. It no longer relies on DOM selection through matching class names and id's to make it work and no longer makes uses of `d3.scaleLinear()`. The SVG structure is improved too, for example, labels and rect's are children of one cell group. In my opinion it's all a lot cleaner and simpler.

I've added text color from the [latest ICS data](https://stratigraphy.org/chart) and added the new periods in the Holocene
I've added breadcrumbs and highlighting of the selected period and its ancestors inspired by [this notebook](https://observablehq.com/@kerryrodden/sequences-icicle).

Things I have yet to tackle are

- [x] Support for dragging
- [x] Show bit of neighbors on focus of period
- [x] Check if everything is up-to-date with latest ICS data
- [x] Enter a period input

And later on
- [x] Standalone non-Observable version
- [x] Publish to npm
- [ ] Switch vertical on narrow screen

**Comment by smithGit** [comment]
Heel erg bedankt!  That is great news.  I wanted to let you know I appreciate this follow-up and I look forward to reviewing everything in more detail.  I will let others I have contacted on this project know, as soon as I have digested the new edition.  

I have only taken an initial look at the time scale 2021 and it looks great –you have included the new period names.  (Note: on this quick review, I was not able to expose the Holocene on Edge or Chrome.)

I am at the moment at our home in northern Michigan with the grandkids and some house projects, so give me a few days.  I was not successful converting to V7, so really appreciate your work!  Note that, instead of working further on eras, I’m working to visualize 36,111 slave voyages from a university site SlaveVoyages.org.  I will let you know how that is going shortly.

Best regards and Gefeliciteerd (if that is the right form of “congratulations”)!  Sam

**Comment by JulesBlm** [comment]
Thanks, "Gefeliciteerd" is indeed form of "congratulations" 😄. See the pull request I just made for a standalone (non-Observable) version of the updated d3 v7 geo timescale: [Standalone d3 v7 version #6](https://github.com/UW-Macrostrat/geo-timescale/pull/6). It doesn't include the "breadcrumbs" that the Observable version has yet.

**Comment by smithGit** [comment]
Jules – this is really nice, and very good to have the stand-alone as well.  Re Quinn’s suggestion re V2 I think is good; It would help to have the work seen as update to Univ. Wisconsin’s Macrostrat (with attribution of your contribution).  I am putting together a more expansive discussion of the progression of visualizations.  New Holocene intervals are most interesting!

I did a bit of comparison, attached – the Observable looks solid, noted only two items highlighted in yellow in the attached.

The stand-alone has an anomaly noted at end of document – time ticks disappear.

**Comment by JulesBlm** [comment]
Closed by pull request https://github.com/UW-Macrostrat/geo-timescale/pull/6. I will make new issues for the remaining bugs

**Comment by smithGit** [comment]
Heel erg bedankt, Jules.  Wish I could help more.
