### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by sebsteinig** [UW-Macrostrat/geo-timescale#4]
Thanks for the great timescale!

Would it be possible to add a license?
 
I know it is a quite old repo, but it seems a couple of people (including me) are interested in updating it to a newer d3 version.

Many thanks!

**Comment by JulesBlm** [comment]
Seconded! I’d like to breathe new life in to this project too. If possible, could I be made a maintainer of this repository @davenquinn ? (Our paths cross again, the intersectection between web and geology just isn’t that big it seems)

**Comment by davenquinn** [comment]
License added (#5)! Sorry I hadn't dealt with this for a while and thanks for the ping @JulesBlm. Small world indeed.
