### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by sebsteinig** [UW-Macrostrat/geo-timescale#8]
I don't know whether this is the right place for this, but I just wasnted to leave a big THANK YOU somewhere for you guys (@davenquinn, @JulesBlm)!

I am really grateful that you shared and updated this time scale. I just started this year with writing my own code and this repo allowed me to finally deploy my first own project. The time scale is just perfect to navigate through our archive of climate model simulations throughout the Phanerozoic.

Just wanted to let you know that your work enabled this in the first place. In case you are interested, you can see how I use the time scale at climatearchive.org.

Many thanks again,

Seb

**Comment by davenquinn** [comment]
Hi Seb, thanks for the shout–out. All credit goes to @JulesBlm on the recent work to keep this alive. We're happy to see this tool in use! Feel free to propose enhancements or modifications!

**Comment by davenquinn** [comment]
@sebsteinig also to note. Your globe is **SO COOL**. Nice work. I'd love to collaborate on future data visualization efforts if you see the opportunity.

**Comment by JulesBlm** [comment]
Wow Seb, your project looks amazing! Super cool! Really glad to see the geotimescale being put to such good use, I sure appreciate it. Thank you! Like Daven said, if you have good ideas for it feel free to ping me or open an issue here. I'm also willing to help on other geoscience visualizations.

And also credits to @jczaplew who started this by developing the first version (using D3 v3) of the timescale at Macrostrat a few years back.
